name: Maintenance
main: com.github.neapovil.maintenance.Maintenance
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/maintenance
depend:
  - CommandAPI
  - Core
permissions:
  maintenance.command.reload:
    default: op
  maintenance.command.set:
    default: op
  maintenance.bypass:
    default: op
